apiVersion: v2
name: hello-world
description: A production-grade Helm chart for the Hello World Go microservice
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Aditya Nutulapati
    url: https://github.com/AdityaNutulapati
keywords:
  - hello-world
  - go
  - microservice
  - prometheus
