################################################################################
# Production overrides
################################################################################

image:
  repository: <AWS_ACCOUNT_ID>.dkr.ecr.ap-south-2.amazonaws.com/lcdt/hello-world
  pullPolicy: Always
  tag: "latest"

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<AWS_ACCOUNT_ID>:role/hello-world-irsa
